# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KOOPERATIF.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, Qt, QPoint
from datetime import datetime
from random import randint, choice

def zamaniCek():
    now = datetime.now()
    tarih_saat = now.strftime("%d.%m.%Y\n%H:%M")
    return tarih_saat

global secim
secim = choice([0,0])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        #MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        MainWindow.setWindowState(Qt.WindowFullScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setAutoFillBackground(False)
        
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: #85b0ff;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"width:192px;\n"
"height:80px;\n"
"background: #628fe3;\n"
"color:#FFF;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"width:192px;\n"
"height:80px;\n"
"background: #2d62c4;\n"
"}")
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 850, 500))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-image:url(\'./img/back.png\');\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.grpGiris = QtWidgets.QGroupBox(self.tab)
        self.grpGiris.setGeometry(QtCore.QRect(0, 0, 801, 401))
        self.grpGiris.setTitle("")
        self.grpGiris.setObjectName("grpGiris")
        self.pushButton_5 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 100, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_11.setGeometry(QtCore.QRect(290, 240, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.btnTemizle = QtWidgets.QPushButton(self.grpGiris)
        self.btnTemizle.setGeometry(QtCore.QRect(290, 310, 64, 64))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(255, 55, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnTemizle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnTemizle.setFont(font)
        self.btnTemizle.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.578947 rgba(255, 55, 55, 255));\n"
"border:2px solid #000;\n"
"}")
        self.btnTemizle.setText("")
        self.btnTemizle.setObjectName("btnTemizle")
        self.pushButton_9 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_9.setGeometry(QtCore.QRect(430, 170, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 170, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 240, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 100, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.btnGiris = QtWidgets.QPushButton(self.grpGiris)
        self.btnGiris.setGeometry(QtCore.QRect(430, 310, 64, 64))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.ReflectSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.578947, QtGui.QColor(45, 209, 51))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnGiris.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnGiris.setFont(font)
        self.btnGiris.setStyleSheet("QPushButton{\n"
"background: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.578947 rgba(45, 209, 51, 255));\n"
"border:2px solid #000;\n"
"}")
        self.btnGiris.setText("")
        self.btnGiris.setObjectName("btnGiris")
        self.lineEdit = QtWidgets.QLineEdit(self.grpGiris)
        self.lineEdit.setGeometry(QtCore.QRect(290, 30, 204, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:2px solid #000;background:#FFF;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 100, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_10.setGeometry(QtCore.QRect(430, 240, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_13.setGeometry(QtCore.QRect(360, 310, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_8 = QtWidgets.QPushButton(self.grpGiris)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 170, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("border:2px solid #000;color:#000;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 801, 401))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 351, 381))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius:8px;background:rgba(255,255,255,170);padding-left:4px;padding-top:4px;")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 421, 381))
        self.groupBox_2.setStyleSheet("border-radius:8px;background:rgba(255,255,255,170);padding-left:4px;padding-top:4px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 201, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 40, 181, 51))
        self.pushButton_14.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 100, 181, 51))
        self.pushButton_15.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 160, 181, 51))
        self.pushButton_16.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 220, 181, 51))
        self.pushButton_17.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setGeometry(QtCore.QRect(10, 280, 181, 51))
        self.pushButton_18.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 10, 201, 361))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 40, 181, 51))
        self.pushButton_19.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 100, 181, 51))
        self.pushButton_20.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 160, 181, 51))
        self.pushButton_21.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 220, 181, 51))
        self.pushButton_22.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 280, 181, 51))
        self.pushButton_23.setStyleSheet("background:#6681b3;border:2px solid #000;color:#000;")
        self.pushButton_23.setObjectName("pushButton_23")
        self.groupBox.raise_()
        self.grpGiris.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 311, 331))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background:rgba(255,255,255,200);border:2px solid #000;")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#000;padding:2px;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(330, 320, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:#000;")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(330, 60, 461, 251))
        self.textEdit.setStyleSheet("background:rgba(255,255,255,200);border:2px solid #000;")
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 781, 381))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("border-radius:8px;background:rgba(255,255,255,170);padding-left:4px;padding-top:4px;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:none;")
        self.label_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:2px solid #000;background:#FFF;border-radius:0;")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 120, 751, 101))
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 721, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background:none;padding:0;")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(270, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 60, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:2px solid #000;background:#FFF;border-radius:0;")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(530, 60, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:2px solid #000;background:#FFF;border-radius:0;color:green;")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(530, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background:none;")
        self.label_7.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 220, 751, 151))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("background:none;")
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 751, 131))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(230)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_3, "")
        self.lblTarih = QtWidgets.QLabel(self.centralwidget)
        self.lblTarih.setGeometry(QtCore.QRect(626, 0, 181, 54))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTarih.setFont(font)
        self.lblTarih.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTarih.setStyleSheet("background:rgba(0,0,0,0);padding:2px;")
        self.lblTarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblTarih.setObjectName("lblTarih")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 40, 73, 28))
        self.label_3.setStyleSheet("background:rgba(0,0,0,0);background-image:url(./img/4g.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(700, 40, 32, 26))
        self.label_4.setStyleSheet("background:rgba(0,0,0,0);background-image:url(./img/wlan.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lblGiris = QtWidgets.QLabel(self.centralwidget)
        self.lblGiris.setGeometry(QtCore.QRect(0, 0, 811, 91))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lblGiris.setFont(font)
        self.lblGiris.setStyleSheet("color:#FFF;background-color:#628fe3;padding-left:80px;\n"
"")
        self.lblGiris.setObjectName("lblGiris")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label_9.setStyleSheet("background:none;background-image:url(./img/logo.png)")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.tabWidget.raise_()
        self.lblGiris.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.lblTarih.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btnGiris.clicked.connect(self.giris)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer = QTimer() 
        self.timer.timeout.connect(self.tarih)
        self.timer.start(500)

        self.blink1 = QTimer() 
        self.blink1.timeout.connect(self.blinkF1)
        sure = randint(100,1000)
        self.blink1.start(sure/1000)
        self.blink2 = QTimer()
        self.blink2.timeout.connect(self.blinkF2)

    def blinkF1(self):
        global secim
        secim = choice([self.label_3,self.label_4])
        sure = randint(100,500)
        secim.setVisible(False)
        self.blink2.start(sure)
        self.blink1.stop()

    def blinkF2(self):
        global secim
        secim.setVisible(True)
        sure = randint(500,2000)
        self.blink1.start(sure)
        self.blink2.stop()

    def tarih(self):
        self.lblTarih.setText(zamaniCek())
        
    def giris(self):
        self.lblGiris.setVisible(False)
        self.grpGiris.setVisible(False)
        self.label_9.setVisible(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SS18 DC_PANEL"))
        self.pushButton_5.setText(_translate("MainWindow", "2"))
        self.pushButton_11.setText(_translate("MainWindow", "7"))
        self.pushButton_9.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "4"))
        self.pushButton_12.setText(_translate("MainWindow", "8"))
        self.pushButton_6.setText(_translate("MainWindow", "1"))
        self.lineEdit.setText(_translate("MainWindow", "1234"))
        self.pushButton_4.setText(_translate("MainWindow", "3"))
        self.pushButton_10.setText(_translate("MainWindow", "9"))
        self.pushButton_13.setText(_translate("MainWindow", "0"))
        self.pushButton_8.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>ŞOFÖR BİLGİLERİ</p><p>Ad Soyad : Atakan Argın</p><p>Bakiye : 1000TL<br/></p><p>HAT BİLGİLERİ</p><p>Hat : SEÇİLMEMİŞ</p><p><br/>DURAKLAR</p><p>Başlangıç : - </p><p>Bitiş : -</p><p>Sonraki : -</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ANONSLAR"))
        self.pushButton_14.setText(_translate("MainWindow", "ARKAYA ILERLEYELIM"))
        self.pushButton_15.setText(_translate("MainWindow", "MASKELERİ TAKALIM"))
        self.pushButton_16.setText(_translate("MainWindow", "ANONS1"))
        self.pushButton_17.setText(_translate("MainWindow", "ANONS2"))
        self.pushButton_18.setText(_translate("MainWindow", "ANONS3"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ÜCRET TOPLAMA"))
        self.pushButton_19.setText(_translate("MainWindow", "ŞOFÖR TAM"))
        self.pushButton_20.setText(_translate("MainWindow", "ÖĞRENCİ"))
        self.pushButton_21.setText(_translate("MainWindow", "+65"))
        self.pushButton_22.setText(_translate("MainWindow", "ÜCRETSİZ"))
        self.pushButton_23.setText(_translate("MainWindow", "STANDART"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Genel"))
        self.listWidget.setSortingEnabled(False)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "1  - FATIH"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "4  - ÇARŞI-BATI"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "9  - ÇARŞI-SDU TIP"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "12 - ÇARŞI-DOĞU"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "40 - OTOGAR-KIZ.KYK"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "37 - ÇARŞI-SDU"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "HAT SEÇİMİ"))
        self.pushButton.setText(_translate("MainWindow", "SEÇ"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Hat detayları;<br />Başlangıç : </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Bitiş : </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Tüm duraklar...</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Hatlar"))
        self.label_5.setText(_translate("MainWindow", "BUS ID"))
        self.lineEdit_2.setText(_translate("MainWindow", "32DC_2898"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Durum Bilgisi"))
        self.label_8.setText(_translate("MainWindow", "Uzak bağlantı açık, cihaz güncel, sinyal kalitesi iyi,\n"
"Senkronizasyon 4dk önce yapılmış, sonraki senkronizasyona 11dk."))
        self.label_6.setText(_translate("MainWindow", "SUNUCU"))
        self.lineEdit_3.setText(_translate("MainWindow", "34.72.128.32"))
        self.lineEdit_4.setText(_translate("MainWindow", "|||||||||"))
        self.label_7.setText(_translate("MainWindow", "SİNYAL"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Güncel Ücret Tarifesi"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kart Tipi"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ücret"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Aktarma"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "KART TİPİ"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "ÜCRET"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "AKTARMA"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "STANDART"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "2.75"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "1.0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "ÖĞRENCİ"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "2.0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "1.0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "65+"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "ÜCRETSİZ"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "ÜCRETSİZ"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Ayarlar"))
        self.lblTarih.setText(_translate("MainWindow", "04.03.2021\n"
"01.38"))
        self.lblGiris.setText(_translate("MainWindow", "KULLANICI GİRİŞİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

